services:
  osurequestor:
    image: osurequestor
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - requestor-net
  request_db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=requestor
      - POSTGRES_PASSWORD=requestor
      - POSTGRES_DB=requestdb
    ports:
      - "2345:5432"
    volumes:
      - ./docker-volume/psql:/var/lib/postgresql/data
    networks:
      - requestor-net

networks:
  requestor-net:
    driver: bridge
